services:
  rabbitmq:
    image: rabbitmq:4.1-management-alpine
    hostname: rabbitmq
    env_file:
      .env
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      .env
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

volumes:
  rabbitmq-data:
    name: rabbit-data
