FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

COPY pyproject.toml uv.lock README.md ./
RUN uv sync --frozen

COPY src /app/src

ENV PYTHONPATH=/app/src
ENV UV_LINK_MODE=copy

CMD ["uv", "run", "faststream", "run", "application.faststream_application.application:app"]
