FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

COPY pyproject.toml ./
COPY common ./common
COPY services ./services
ENV UV_LINK_MODE=copy
RUN uv lock && uv sync --frozen

CMD ["uv", "run", "--package", "store-service", "faststream", "run", "store_service.application.faststream_app:app"]
